stages:
  download_data:
    cmd: python scripts/download_data.py --output data/raw/evasionbench.parquet --revision main
    deps:
      - scripts/download_data.py
      - src/data.py
    outs:
      - data/raw/evasionbench.parquet

  validate_data:
    cmd: python scripts/validate_dataset.py --data data/raw/evasionbench.parquet --contract data/contracts/evasionbench_manifest.json
    deps:
      - scripts/validate_dataset.py
      - src/data.py
      - data/raw/evasionbench.parquet
      - data/contracts/evasionbench_manifest.json

  prepare_data:
    cmd: python scripts/prepare_data.py --input data/raw/evasionbench.parquet --output data/processed/evasionbench_prepared.parquet
    deps:
      - scripts/prepare_data.py
      - data/raw/evasionbench.parquet
      - data/contracts/evasionbench_manifest.json
    outs:
      - data/processed/evasionbench_prepared.parquet

  analyze_core_stats:
    cmd: python scripts/analyze_core_stats.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase3
    deps:
      - scripts/analyze_core_stats.py
      - src/analysis/core_stats.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase3/core_stats

  analyze_lexical:
    cmd: python scripts/analyze_lexical.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase3
    deps:
      - scripts/analyze_lexical.py
      - src/analysis/lexical.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase3/lexical

  analyze_linguistic_quality:
    cmd: python scripts/analyze_linguistic_quality.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase3
    deps:
      - scripts/analyze_linguistic_quality.py
      - src/analysis/linguistic_quality.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase3/linguistic_quality

  analyze_phase3:
    cmd: python scripts/run_phase3_analyses.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase3 --families all
    deps:
      - scripts/run_phase3_analyses.py
      - scripts/analyze_core_stats.py
      - scripts/analyze_lexical.py
      - scripts/analyze_linguistic_quality.py
      - src/analysis/artifacts.py
      - src/analysis/core_stats.py
      - src/analysis/lexical.py
      - src/analysis/linguistic_quality.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase3/artifact_index.json

  analyze_qa_semantic:
    cmd: python scripts/analyze_qa_semantic.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase4
    deps:
      - scripts/analyze_qa_semantic.py
      - src/analysis/qa_semantic.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase4/semantic_similarity

  analyze_topics:
    cmd: python scripts/analyze_topics.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase4 --topics 8 --seed 42
    deps:
      - scripts/analyze_topics.py
      - src/analysis/topic_modeling.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase4/topic_modeling

  analyze_question_behavior:
    cmd: python scripts/analyze_question_behavior.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase4
    deps:
      - scripts/analyze_question_behavior.py
      - src/analysis/question_behavior.py
      - src/analysis/artifacts.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase4/question_behavior

  analyze_phase4:
    cmd: python scripts/run_phase4_analyses.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/analysis/phase4 --families all
    deps:
      - scripts/run_phase4_analyses.py
      - scripts/analyze_qa_semantic.py
      - scripts/analyze_topics.py
      - scripts/analyze_question_behavior.py
      - src/analysis/artifacts.py
      - src/analysis/qa_semantic.py
      - src/analysis/topic_modeling.py
      - src/analysis/question_behavior.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/analysis/phase4/artifact_index.json

  phase5_logreg:
    cmd: python scripts/run_classical_baselines.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase5 --families logreg
    deps:
      - scripts/run_classical_baselines.py
      - scripts/run_experiment.py
      - src/models.py
      - src/evaluation.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase5/logreg

  phase5_tree:
    cmd: python scripts/run_classical_baselines.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase5 --families tree
    deps:
      - scripts/run_classical_baselines.py
      - scripts/train_tree_baseline.py
      - src/models.py
      - src/evaluation.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase5/tree

  phase5_boosting:
    cmd: python scripts/run_classical_baselines.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase5 --families boosting
    deps:
      - scripts/run_classical_baselines.py
      - scripts/train_tree_baseline.py
      - src/models.py
      - src/evaluation.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase5/boosting

  phase5_compare:
    cmd: python scripts/compare_classical_models.py --input-root artifacts/models/phase5 --output-root artifacts/models/phase5/model_comparison
    deps:
      - scripts/compare_classical_models.py
      - src/visualization.py
      - artifacts/models/phase5/logreg
      - artifacts/models/phase5/tree
      - artifacts/models/phase5/boosting
    outs:
      - artifacts/models/phase5/model_comparison

  phase5:
    cmd: python scripts/run_classical_baselines.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase5 --families all --compare
    deps:
      - scripts/run_classical_baselines.py
      - scripts/compare_classical_models.py
      - src/models.py
      - src/evaluation.py
      - src/visualization.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase5/run_summary.json

  phase8_optimize:
    cmd: python scripts/run_model_optimization.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase8 --families all --selection-metric f1_macro --accuracy-floor 0.6431560071727436
    deps:
      - scripts/run_model_optimization.py
      - src/evaluation.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase8/selected_model.json

  phase6_transformer:
    cmd: python scripts/run_transformer_baselines.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/models/phase6/transformer --max-epochs 3 --learning-rate 2e-5
    deps:
      - scripts/run_transformer_baselines.py
      - src/models.py
      - src/evaluation.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/models/phase6/transformer

  phase6_xai_classical:
    cmd: python scripts/run_explainability_analysis.py --data data/processed/evasionbench_prepared.parquet --models-root artifacts/models/phase5 --output-root artifacts/explainability/phase6 --families all
    deps:
      - scripts/run_explainability_analysis.py
      - src/explainability.py
      - artifacts/models/phase5/logreg
      - artifacts/models/phase5/tree
      - artifacts/models/phase5/boosting
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/explainability/phase6/xai_summary.json

  phase6_xai_transformer:
    cmd: python scripts/run_transformer_explainability.py --model-path artifacts/models/phase6/transformer/model --data-path data/processed/evasionbench_prepared.parquet --output-root artifacts/explainability/phase6/transformer --n-samples 20
    deps:
      - scripts/run_transformer_explainability.py
      - src/explainability.py
      - artifacts/models/phase6/transformer
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/explainability/phase6/transformer/transformer_xai.json
      - artifacts/explainability/phase6/transformer/transformer_xai_summary.json
      - artifacts/explainability/phase6/transformer/transformer_xai.html

  phase6_label_diagnostics:
    cmd: python scripts/run_label_diagnostics.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/diagnostics/phase6 --random-state 42
    deps:
      - scripts/run_label_diagnostics.py
      - src/models.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/diagnostics/phase6/suspect_examples.csv
      - artifacts/diagnostics/phase6/outlier_examples.csv
      - artifacts/diagnostics/phase6/label_diagnostics_summary.json
      - artifacts/diagnostics/phase6/label_diagnostics_report.md

  phase7_report_pipeline:
    cmd: python3 scripts/run_research_pipeline.py --input data/processed/evasionbench_prepared.parquet --output-root artifacts/reports/phase7 --skip-existing
    deps:
      - scripts/run_research_pipeline.py
      - scripts/build_report_manifest.py
      - scripts/run_phase3_analyses.py
      - scripts/run_phase4_analyses.py
      - scripts/run_classical_baselines.py
      - scripts/run_transformer_baselines.py
      - scripts/run_explainability_analysis.py
      - scripts/run_transformer_explainability.py
      - scripts/run_label_diagnostics.py
      - data/processed/evasionbench_prepared.parquet
    outs:
      - artifacts/reports/phase7/provenance_manifest.json
      - artifacts/reports/phase7/run_summary.json
